### ISSUE TITLE
Visualization options not working

### ISSUE THREAD

**Issue by limdor** [limdor/quoniam#1]
The visualization of the bounding boxes, bounding spheres and the option to deactivate the visulization of the sphere of viewpoint when it's present doesn't work.

**Comment by 2017Greg** [comment]
did you solve the problem? I met the same problem recently. Please contact me if you have any solutions.
thank you very much.

**Comment by limdor** [comment]
I did not check again but I can take a look to see how difficult is to fix it

**Comment by limdor** [comment]
@2017Greg I will have to do some structural changes to fix the visualization options but it looks that it should not be a big issue to be fixed, I will just need to find time to work on it.

**Comment by limdor** [comment]
@2017Greg I finished the structural changes and now I can start checking what is the problem. In some cases it is already working but it some others I will have to add some more debugging to be able to see what's going on.
Is there some of the visualization options that you are more interested than others? For me it is the same to start with one or the other.
